---
- name: all
  hosts: all
  sudo: no
  roles:
    - { role: check,    tags: ['check'] }
    - { role: init,     tags: ['init'] }
    - { role: useradd,  tags: ['useradd'] }
    - { role: chatwork, tags: ['chatwork'] }
    - { role: yum-repo, tags: ['yum-repo'] }
    - { role: nginx,    tags: ['nginx'] }
    - { role: php56,      tags: ['php56'] }
    - { role: php56-fpm,  tags: ['php56-fpm'] }
