---
- name: "check ip4"
  debug: msg="{{ item }}"
  with_items: ansible_all_ipv4_addresses

- name: "check date"
  debug: msg='{{ ansible_date_time.date }} {{ ansible_date_time.time }} {{ ansible_date_time.tz }}'
