---
- name: Install libwebp by epel
  sudo: yes
  yum: name="{{ item }}" state=present enablerepo=epel
  with_items:
    - libwebp

- name: Install
  sudo: yes
  yum: name="{{ item }}" state=present disablerepo=epel enablerepo=remi,remi-php56
  with_items: "packages.{{ansible_distribution}}"
  when: ansible_distribution == 'CentOS'

- name: Install
  sudo: yes
  yum: name="{{ item }}" state=present disablerepo=epel
  with_items: "packages.{{ansible_distribution}}"
  when: ansible_distribution == 'Amazon'

- name: php.ini configuration
  sudo: yes
  ini_file: >
    dest=/etc/php.ini
    section="{{item.section}}"
    option="{{item.option}}"
    value="{{item.value}}"
  with_items: php_ini
