---
- name: Install
  sudo: yes
  yum: name={{item}} state=present
  with_items: repo_url
  when: ansible_distribution != 'Amazon'

- name: SET disanabled
  sudo: yes
  lineinfile: >-
    dest={{item}}
    state=present
    regexp="^#?enabled.*?=.*"
    line="enabled = 0"
  with_items: repo_path
  when: ansible_distribution != 'Amazon'
