---
- name: init Install
  sudo: yes
  yum: name={{item}} state=present
  with_items: yum_list

- name: set zone to /etc/sysconfig/clock
  sudo: yes
  replace: >
    dest=/etc/sysconfig/clock
    regexp='^ZONE=.*'
    replace='ZONE="{{ zone }}"'
  when: not (ansible_distribution == "CentOS" and ansible_distribution_major_version == "7")

- name: set UTC to /etc/sysconfig/clock
  sudo: yes
  replace: >
    dest=/etc/sysconfig/clock
    regexp='^UTC=.*'
    replace='UTC={{ utc }}'
  when: not (ansible_distribution == "CentOS" and ansible_distribution_major_version == "7")

- name: init Set TimeZone
  sudo: yes
  file: src={{ timezone }} dest=/etc/localtime state=link force=yes mode='u=rw,go=r'
  notify: restart crond
  when: not (ansible_distribution == "CentOS" and ansible_distribution_major_version == "7")

- name: init Set logrotate format
  sudo: yes
  lineinfile: >-
    dest=/etc/logrotate.conf
    regexp='^#?dateext|^#?nodateext'
    line='nodateext'

- name: init Set cloud.cfg
  sudo: yes
  lineinfile: >-
    dest=/etc/cloud/cloud.cfg
    regexp='^repo_upgrade.*'
    line='repo_upgrade: none'
  when: ansible_distribution == 'Amazon'

- name: init CommentOut net.bridge.bridge-nf-call-*
  sudo: yes
  replace: dest=/etc/sysctl.conf regexp='^net.bridge.bridge-nf-call-' replace='#net.bridge.bridge-nf-call-'

- name: init Set Sysctl
  sudo: yes
  sysctl: name='{{item.key}}' value='{{item.value}}' state=present reload=yes
  with_dict: sysctl

- name: init Set visudo template
  sudo: yes
  template: src=0-wheel-init dest=/etc/sudoers.d/0-wheel-init mode='ug=r,o='
